# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#define stages

jobs:
  conatiner-test:
    runs-on: github_action
    steps:
      - name: Pull Python Docker image
        run: docker pull python:3.10.12

      - name: Run Python container and output Python version
        run: |
          docker run --rm python:3.10.12 python --version
#jobs:
  # This workflow contains a single job called "build"
  #Test:
    # The type of runner that the job will run on
    #runs-on: redhat

    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
      # Runs a single command using the runners shell
      #- name: Run a one-line script
        #run: cat /etc/redhat-release
